# Generated by Django 5.1.3 on 2025-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0002_remove_review_building_alter_building_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='title',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
