# Generated by Django 5.1.3 on 2025-02-20 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0003_building_title_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myRoom.building'),
        ),
    ]
