# Generated by Django 5.1.5 on 2025-02-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0002_alter_photo_image'),
        ('myRoom', '0006_alter_review_room'),
    ]

    operations = [
    ]
