# Generated by Django 5.1.3 on 2025-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0009_remove_tag_building_remove_tag_room_review_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='building_tags', to='myRoom.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='room_tags', to='myRoom.tag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='review_tags', to='myRoom.tag'),
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
