# Generated by Django 5.1.3 on 2025-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0010_building_tags_room_tags_alter_review_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Test Title', max_length=100),
            preserve_default=False,
        ),
    ]
