# Generated by Django 5.1.3 on 2025-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0013_review_date_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
