# Generated by Django 5.1.3 on 2025-03-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0014_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
