# Generated by Django 5.1.3 on 2025-03-03 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0015_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myRoom.building'),
        ),
    ]
