# Generated by Django 5.1.5 on 2025-03-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0016_alter_review_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='description',
        ),
    ]
