# Generated by Django 5.1.5 on 2025-03-12 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0017_remove_building_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
