# Generated by Django 5.1.5 on 2025-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0018_alter_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userReview',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
