# Generated by Django 5.1.7 on 2025-03-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0017_profile'),
        ('myRoom', '0019_alter_review_rating'),
        ('myRoom', '0019_alter_review_userreview_alter_room_title'),
    ]

    operations = [
    ]
