# Generated by Django 5.1.5 on 2025-03-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0019_alter_review_rating'),
        ('myRoom', '0019_alter_review_userreview_alter_room_title'),
    ]

    operations = [
    ]
