# Generated by Django 5.1.5 on 2025-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0020_merge_20250319_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userReview',
            field=models.TextField(),
        ),
    ]
