# Generated by Django 5.1.3 on 2025-03-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0017_profile'),
        ('myRoom', '0021_alter_review_userreview'),
    ]

    operations = [
    ]
