# Generated by Django 5.1.7 on 2025-03-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0020_merge_20250319_1143'),
        ('myRoom', '0022_merge_0017_profile_0021_alter_review_userreview'),
    ]

    operations = [
    ]
