# Generated by Django 5.1.3 on 2025-03-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0024_alter_profile_image'),
        ('myRoom', '0030_alter_profile_image'),
    ]

    operations = [
    ]
