# Generated by Django 5.1.5 on 2025-03-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0024_room_roomnum_alter_profile_image'),
        ('myRoom', '0031_merge_20250322_0049'),
        ('myRoom', '0031_merge_20250322_1258'),
    ]

    operations = [
    ]
