# Generated by Django 5.1.3 on 2025-03-25 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRoom', '0032_merge_20250322_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myRoom.review'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomNum',
            field=models.CharField(max_length=100),
        ),
    ]
